### ISSUE TITLE
Couldn’t build with make

### ISSUE THREAD

**Issue by NV** [wjlroe/lannister#1]
```
➤ make
Makefile:1: /src/Make.inc: No such file or directory
Makefile:7: /src/Make.cmd: No such file or directory
make: *** No rule to make target `/src/Make.cmd'.  Stop.
```

Looks like somebody forgot to commit `src` directory.

**Comment by wjlroe** [comment]
Ah, actually those includes are from Go. An old prerelease. The build system is easier these days I think and the Makefile needs updating (not to mention the code is probably likewise out of sync with Go).

**Comment by NV** [comment]
I’m actually working on Jekyll blog with pjax. It’s a bit of a challenge since [Jekyll doesn’t really multiplex content/templates](https://github.com/imathis/octopress/issues/772). You have to monkey patch to make it work.

Lannister came out as first result for "[pjax static website](https://www.google.com/search?q=pjax+static+website)" in Google.

**Comment by wjlroe** [comment]
Ah well If I was doing that, then I'd try out https://github.com/rails/turbolinks
No server side changes necessary, removing the main PITA that PJAX requires so much messing around. Seems like a pretty good option to me - although YMMV, I haven't tried it out yet.

I'd like to mix turbolinks with Octopress myself at some point, because I use octopress for my blog and the speed increase of PJAX-style page loading is tempting.

**Comment by NV** [comment]
Thanks for the link. Although it won’t work for me since I use animation to transition from one page to another.

P.S. Cudos for Game of Thrones characters project names.
